name: CI
on: [push]
jobs:
  build:
    name: Check quality and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults: 
    run:
      working-directory: lottamoberg.com
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and Test
        uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn test
